---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alspin.
--- DateTime: 29/12/2023 17:22
---
---
local function create_resource_rule(name)
    rule("resource." .. name)
    before_build(function (opt)
        os.cp("$(projectdir)/resource/" .. name .. "/*", "$(buildir)/$(plat)/$(arch)/$(mode)/resource/" .. name .. "/")
    end)
end

create_resource_rule("shader")
create_resource_rule("texture")
create_resource_rule("model")